set ( SYSTEM_SUB_INCLUDE_DIR ${SYSTEM_INCLUDE_DIR}/System )
set ( SYSTEM_SUB_SOURCE_DIR ${SYSTEM_SOURCE_DIR}/System )

set ( SYSTEM_FILES
    ${SYSTEM_FILES}
    ${SYSTEM_INCLUDE_DIR}/System.hpp
)